-- Database Creation
CREATE DATABASE Products;

-- Database Set Up
USE Products;

CREATE TABLE Product(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	Name VARCHAR(100) NOT NULL
);

CREATE TABLE Category(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	Name VARCHAR(100) NOT NULL
);

CREATE TABLE ProductCategory(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	ProductId INT NOT NULL FOREIGN KEY REFERENCES Product(Id),
	CategoryId INT NOT NULL FOREIGN KEY REFERENCES Category(Id)
);


-- Insert section is generated by ChatGPT
-- Insert Products
INSERT INTO Product (Name) VALUES ('ProductA');
INSERT INTO Product (Name) VALUES ('ProductB');
INSERT INTO Product (Name) VALUES ('ProductC');
INSERT INTO Product (Name) VALUES ('ProductD');
INSERT INTO Product (Name) VALUES ('ProductE');
INSERT INTO Product (Name) VALUES ('ProductF');
INSERT INTO Product (Name) VALUES ('ProductG');
INSERT INTO Product (Name) VALUES ('ProductH');
INSERT INTO Product (Name) VALUES ('ProductI');
INSERT INTO Product (Name) VALUES ('ProductJ');
INSERT INTO Product (Name) VALUES ('ProductK');
INSERT INTO Product (Name) VALUES ('ProductL');
INSERT INTO Product (Name) VALUES ('ProductM');
INSERT INTO Product (Name) VALUES ('ProductN');
INSERT INTO Product (Name) VALUES ('ProductO');
INSERT INTO Product (Name) VALUES ('ProductP');
INSERT INTO Product (Name) VALUES ('ProductQ');
INSERT INTO Product (Name) VALUES ('ProductR');
INSERT INTO Product (Name) VALUES ('ProductS');
INSERT INTO Product (Name) VALUES ('ProductT');

-- Insert Categories
INSERT INTO Category (Name) VALUES ('Category1');
INSERT INTO Category (Name) VALUES ('Category2');
INSERT INTO Category (Name) VALUES ('Category3');
INSERT INTO Category (Name) VALUES ('Category4');
INSERT INTO Category (Name) VALUES ('Category5');
INSERT INTO Category (Name) VALUES ('Category6');
INSERT INTO Category (Name) VALUES ('Category7');
INSERT INTO Category (Name) VALUES ('Category8');
INSERT INTO Category (Name) VALUES ('Category9');
INSERT INTO Category (Name) VALUES ('Category10');
INSERT INTO Category (Name) VALUES ('Category11');
INSERT INTO Category (Name) VALUES ('Category12');
INSERT INTO Category (Name) VALUES ('Category13');
INSERT INTO Category (Name) VALUES ('Category14');
INSERT INTO Category (Name) VALUES ('Category15');
INSERT INTO Category (Name) VALUES ('Category16');
INSERT INTO Category (Name) VALUES ('Category17');
INSERT INTO Category (Name) VALUES ('Category18');
INSERT INTO Category (Name) VALUES ('Category19');
INSERT INTO Category (Name) VALUES ('Category20');

-- Insert ProductCategory connections
-- Product A
INSERT INTO ProductCategory (ProductId, CategoryId) VALUES (1, 1);
INSERT INTO ProductCategory (ProductId, CategoryId) VALUES (1, 2);

-- Product B
INSERT INTO ProductCategory (ProductId, CategoryId) VALUES (2, 2);
INSERT INTO ProductCategory (ProductId, CategoryId) VALUES (2, 3);
INSERT INTO ProductCategory (ProductId, CategoryId) VALUES (2, 4);

-- Product C
INSERT INTO ProductCategory (ProductId, CategoryId) VALUES (3, 5);

-- Product D
INSERT INTO ProductCategory (ProductId, CategoryId) VALUES (4, 6);
INSERT INTO ProductCategory (ProductId, CategoryId) VALUES (4, 7);
INSERT INTO ProductCategory (ProductId, CategoryId) VALUES (4, 8);

-- Product E
INSERT INTO ProductCategory (ProductId, CategoryId) VALUES (5, 9);
INSERT INTO ProductCategory (ProductId, CategoryId) VALUES (5, 10);
INSERT INTO ProductCategory (ProductId, CategoryId) VALUES (5, 11);
INSERT INTO ProductCategory (ProductId, CategoryId) VALUES (5, 12);

-- Product F
-- No category

-- Product G
INSERT INTO ProductCategory (ProductId, CategoryId) VALUES (7, 13);

-- Product H
INSERT INTO ProductCategory (ProductId, CategoryId) VALUES (8, 14);
INSERT INTO ProductCategory (ProductId, CategoryId) VALUES (8, 15);

-- Product I
INSERT INTO ProductCategory (ProductId, CategoryId) VALUES (9, 16);
INSERT INTO ProductCategory (ProductId, CategoryId) VALUES (9, 17);
INSERT INTO ProductCategory (ProductId, CategoryId) VALUES (9, 18);

-- Product J
INSERT INTO ProductCategory (ProductId, CategoryId) VALUES (10, 19);
INSERT INTO ProductCategory (ProductId, CategoryId) VALUES (10, 20);

-- Product K
INSERT INTO ProductCategory (ProductId, CategoryId) VALUES (11, 1);
INSERT INTO ProductCategory (ProductId, CategoryId) VALUES (11, 2);
INSERT INTO ProductCategory (ProductId, CategoryId) VALUES (11, 3);
INSERT INTO ProductCategory (ProductId, CategoryId) VALUES (11, 4);
INSERT INTO ProductCategory (ProductId, CategoryId) VALUES (11, 5);

-- Product L
-- No category

-- Product M
INSERT INTO ProductCategory (ProductId, CategoryId) VALUES (13, 6);
INSERT INTO ProductCategory (ProductId, CategoryId) VALUES (13, 7);

-- Product N
INSERT INTO ProductCategory (ProductId, CategoryId) VALUES (14, 8);
INSERT INTO ProductCategory (ProductId, CategoryId) VALUES (14, 9);
INSERT INTO ProductCategory (ProductId, CategoryId) VALUES (14, 10);

-- Product O
-- No category

-- Product P
INSERT INTO ProductCategory (ProductId, CategoryId) VALUES (16, 11);
INSERT INTO ProductCategory (ProductId, CategoryId) VALUES (16, 12);
INSERT INTO ProductCategory (ProductId, CategoryId) VALUES (16, 13);

-- Product Q
-- No category

-- Product R
INSERT INTO ProductCategory (ProductId, CategoryId) VALUES (18, 14);
INSERT INTO ProductCategory (ProductId, CategoryId) VALUES (18, 15);
INSERT INTO ProductCategory (ProductId, CategoryId) VALUES (18, 16);

-- Product S
INSERT INTO ProductCategory (ProductId, CategoryId) VALUES (19, 17);
INSERT INTO ProductCategory (ProductId, CategoryId) VALUES (19, 18);
INSERT INTO ProductCategory (ProductId, CategoryId) VALUES (19, 19);
INSERT INTO ProductCategory (ProductId, CategoryId) VALUES (19, 20);

-- Product T
INSERT INTO ProductCategory (ProductId, CategoryId) VALUES (20, 1);
INSERT INTO ProductCategory (ProductId, CategoryId) VALUES (20, 2);
INSERT INTO ProductCategory (ProductId, CategoryId) VALUES (20, 3);


-- Query: Select all pairs "Product-Category" even if there are no categories
SELECT Product.Name, Category.Name
FROM Product
LEFT JOIN ProductCategory ON Product.Id = ProductCategory.ProductId
LEFT JOIN Category ON ProductCategory.CategoryId = Category.Id